name: flutter_advanced_segment_example
description: Demonstrates how to use the flutter_advanced_segment plugin.
publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flex_color_scheme: ^6.1.2  

  flutter_advanced_segment:
    path: ../

flutter:
  uses-material-design: true
