name: flutter_advanced_segment_example
description: Demonstrates how to use the flutter_advanced_segment plugin.
publish_to: 'none'

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flex_color_scheme: ^7.3.1 

  flutter_advanced_segment:
    path: ../

flutter:
  uses-material-design: true
